# Generated by Django 5.0.4 on 2024-04-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("sobre_nome", models.CharField(max_length=60)),
                ("data_de_nascimento", models.DateTimeField()),
                ("genero", models.IntegerField()),
                ("cartao_sus", models.CharField(max_length=15, unique=True)),
                ("telefone", models.CharField(max_length=14)),
                ("rua", models.CharField(max_length=60)),
                ("numero", models.IntegerField()),
                ("complemento", models.CharField(max_length=60)),
                ("ponto_referencia", models.CharField(max_length=50)),
                ("status", models.IntegerField(default=1)),
                ("data_criacao", models.DateTimeField()),
                ("data_alteracao", models.DateTimeField()),
            ],
            options={
                "db_table": "pacientes",
            },
        ),
    ]
