# Generated by Django 5.0.4 on 2024-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_alter_paciente_data_alteracao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="sobre_nome",
        ),
        migrations.AddField(
            model_name="paciente",
            name="agendamento_fixo",
            field=models.IntegerField(choices=[(1, "SIM"), (2, "Não")], default=1),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="complemento",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Feminino"), (2, "Masculino"), (3, "Outros")]
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="ponto_referencia",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="rua",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(max_length=18),
        ),
    ]
