# Generated by Django 5.0.4 on 2024-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_alter_paciente_data_de_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
