# Generated by Django 5.0.4 on 2024-04-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0006_alter_paciente_data_de_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Feminino"), (2, "Masculino"), (3, "Outros")], null=True
            ),
        ),
    ]
