# Generated by Django 5.0.4 on 2024-04-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0007_alter_paciente_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="numero",
            field=models.IntegerField(null=True),
        ),
    ]
