# Generated by Django 5.0.4 on 2024-04-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0008_alter_paciente_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_de_nascimento",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Feminino"), (2, "Masculino"), (3, "Outros")], default=None
            ),
        ),
    ]
