# Generated by Django 5.0.4 on 2024-04-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0010_remove_paciente_cartao_sus"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="cartao_sus",
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
