# Generated by Django 5.0.4 on 2024-04-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0011_paciente_cartao_sus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_de_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
