# Generated by Django 5.0.4 on 2024-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0014_alter_paciente_cartao_sus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="cartao_sus",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="data_de_nascimento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.IntegerField(
                choices=[(1, "Feminino"), (2, "Masculino"), (3, "Outros")]
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="numero",
            field=models.IntegerField(),
        ),
    ]
