# Generated by Django 5.0.4 on 2024-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0015_alter_paciente_cartao_sus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="complemento",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="numero",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="ponto_referencia",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="rua",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(max_length=13),
        ),
    ]
