# Generated by Django 5.0.4 on 2024-04-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0016_alter_paciente_complemento_alter_paciente_numero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="agendamento_fixo",
            field=models.IntegerField(choices=[(1, "SIM"), (2, "Não")]),
        ),
    ]
