# Generated by Django 5.0.4 on 2024-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0018_alter_paciente_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="agendamento_fixo",
            field=models.IntegerField(choices=[(1, "Sim"), (2, "Não")]),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="complemento",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="ponto_referencia",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
