# Generated by Django 5.0.4 on 2024-05-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0019_alter_paciente_agendamento_fixo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={"ordering": ["-data_criacao"]},
        ),
    ]
