# Generated by Django 5.0.4 on 2025-04-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                ("data_de_nascimento", models.DateField()),
                (
                    "genero",
                    models.IntegerField(
                        choices=[(1, "Feminino"), (2, "Masculino"), (3, "Outros")]
                    ),
                ),
                ("mae", models.CharField(max_length=60)),
                ("pai", models.CharField(max_length=60)),
                ("email", models.CharField(max_length=60, unique=True)),
                ("celular", models.CharField(max_length=14)),
                ("registro_do_aluno", models.CharField(max_length=11, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pendente"),
                            (2, "Ativo"),
                            (3, "Inativo"),
                            (4, "Removido"),
                        ],
                        default=1,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_alteracao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "estudantes",
            },
        ),
    ]
