# Generated by Django 5.0.4 on 2024-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transporte",
            old_name="observação",
            new_name="observacao",
        ),
        migrations.AlterField(
            model_name="transporte",
            name="motivo_de_transporte",
            field=models.IntegerField(
                choices=[
                    (0, "--Selecione--"),
                    (1, "Retorno"),
                    (2, "Exames"),
                    (3, "Quimioterapia"),
                    (4, "Internação"),
                    (5, "Procedimento"),
                    (6, "Radioterapia"),
                    (7, "Primeira-Consulta"),
                    (8, "Outros"),
                ]
            ),
        ),
    ]
