# Generated by Django 5.0.4 on 2025-04-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportes", "0002_rename_observação_transporte_observacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transporte",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Agendado"), (2, "Cancelado"), (3, "Realizado")], default=1
            ),
        ),
    ]
